### ISSUE TITLE
Works with Qt Creator 4.8.1

### ISSUE THREAD

**Issue by jeandet** [CoatiSoftware/qtc-sourcetrail#9]
I tested with Qt Creator 4.8.1 and it works. On some linux distributions like Fedora, Qt5's qmake is suffixed, maybe the build script could be like:

```
if [ -x "$(command -v qmake-qt5)" ]; then
    export QMAKE=qmake-qt5
elif [ -x "$(command -v qmake)" ]; then
    export QMAKE=qmake
else
    echo "Neither qmake nor qmake-qt5 found"
    exit
fi

$QMAKE qtc-sourcetrail.pro -r "QTC_SOURCE=qt-src" "QTC_BUILD=qt-bin/lib/qtcreator" "LIBS+=-Lqt-bin/lib/qtcreator" "OUTPUT_PATH=output"

```

**Comment by mlangkabel** [comment]
Hi @jeandet, sorry for letting you wait, and thank you very much for testing! 

So this would just be a change in the build.sh script and I guess that the travis CI scripts can stay as they are because we have control over what they run.

Do you want to provide a pull request? If not, let me know and I will prepare one. In that case I would like to ask you to review and test it before we merge it.

**Comment by mlangkabel** [comment]
The merge of your pull request worked fine, thanks again for providing it!
